### ISSUE TITLE
cell segmentation strategy

### ISSUE THREAD

**Issue by wangjiawen2013** [gustaveroussy/sopa#109]
Hi,
Can we perform cell segmentation using DAPI nucleus staining, and then cell membrane staining for the cells that don't have clear DAPI staining ? This is also the strategy adopted by xenium:

The segmentation results are prioritized in this order for each cell:

Segment cells based on their cell boundary stain: The inferred segmentation from this method should be closest to the true cell membrane boundary. It uses cell-surface marker antibodies to target epithelial markers (ATP1A1, E-Cadherin) and immune markers (pan-lymphocyte: CD45). This method can split nuclei, define cells missing a nucleus, and identify multinucleate cells. Nuclei that overlap with anucleate cells are assigned to the cell.
Segment cells based on expansion from the nucleus to the cell interior stain edge: This method includes both a deep learning model and a nuclear expansion method using the interior stain to infer cell boundaries. It uses the interior stain (18S rRNA marker) and the DAPI stain for nuclei. The XOA v3.0 cell segmentation algorithm does not currently use the interior protein stain (alphaSMA/Vimentin), as the 18S marker has been sufficient for most tissue types. The inferred cell outline may look irregular in cases where boundaries between cell interior stains are challenging to identify (i.e., for dense tissue types).
Nuclear expansion: For cases where cells that do not have boundary or interior stains, segment cells with a nuclear (DAPI) expansion distance of 5 µm or until another cell boundary is encountered (described more [below](https://www.10xgenomics.com/support/software/xenium-onboard-analysis/latest/algorithms-overview/segmentation#seg-nucleus-expansion)).

**Comment by quentinblampey** [comment]
Hi @wangjiawen2013, yes, this is possible. There is a [tutorial here](https://gustaveroussy.github.io/sopa/tutorials/advanced_segmentation/#multi-step-segmentation) that details how to do it. 

Let me know if you experience any issues or need more help to do that!

**Comment by quentinblampey** [comment]
I'm closing the issue, as it is inactive, but feel free to re-open if desired!
