### ISSUE TITLE
cell density in sopa.spatial.niches_geometry_stats

### ISSUE THREAD

**Issue by Debohay** [gustaveroussy/sopa#113]
Hi, 

I would like to output the cell density per niche as seen in fig4b of the paper, but I don't see this plot option in the function niches_geometry_stats.

Thanks for the help,
Deborah

**Comment by quentinblampey** [comment]
Hi Deborah,
The cell density from the paper is the division from the cell count per niche (e.g., this can be obtained via `adata.obs["niche"].value_counts()`) and the total area per niche (`df_niches_geometries ["area"]`).
I hope this help, let me know if you need extra information or more details!

**Comment by Debohay** [comment]
Hi Quentin,
This helps, thanks!

**Comment by quentinblampey** [comment]
Great! I'm closing this issue, but don't hesitate to re-open if needed 🙂
