### ISSUE TITLE
CLI tutorial Baysor segmentation creates different number of patches

### ISSUE THREAD

**Issue by Marius1311** [gustaveroussy/sopa#119]
## Description
I'm running the CLI tutorial, and when I create patches for Baysor using 
`sopa patchify baysor tuto.zarr --config-path config.toml --patch-width-microns 1200 --patch-overlap-microns 50`
 
it creates only a single patch, contrary to the 4 patches the tutorial suggests. Where can I actually find the conversion from pixels to microns? 

I played around a bit and found that `sopa patchify baysor tuto.zarr --config-path config.toml --patch-width-microns 200 --patch-overlap-microns 20` actually gives 4 patches.

**Comment by Marius1311** [comment]
Thank you @quentinblampey !

**Comment by KunHHE** [comment]
Can I keep asking a question @quentinblampey @Marius1311 So for sopa patchify image before cellpose, it runs --patch-width-pixel 6000 --patch-overlap-pixel 150, so this is based on pixel; whereas running sopa patchify baysor --patch-width-microns 1200 --patch-overlap-microns 50, so this is microns. Does it correct running like this pixel for cellpose patchify; microns for Baysor patchify? Thanks!!!

**Comment by quentinblampey** [comment]
Yes @KunHHE, this is correct! Indeed, we create patches based on the pixels of the image for cellpose, while, for Baysor, we create patches based on the transcripts (whose coordinates are generally in microns)
