### ISSUE TITLE
[Feature] Conda packaging

### ISSUE THREAD

**Issue by lecorguille** [gustaveroussy/sopa#135]
**Is your feature request related to a problem? Please describe.**
I had the request to install Sopa for the sincellte course (it should tell you something @quentinblampey ? 😉)
We only support Conda and exceptionaly Apptainer

**Describe the solution you'd like**
Can you consider to package Sopa in the long-well-establish Bioconda repository?
Rather easy with `conda skeleton pypi <packagename>`  https://bioconda.github.io/contributor/guidelines.html#python

**Describe alternatives you've considered**
The lazy solution will be install with pip in a conda env but it's the poor solution for a software publicy and FAIRness

**Additional context**
It's urgent 🚨

**Comment by quentinblampey** [comment]
Hello @lecorguille,

Sorry for the delay, I was on vacation. Thanks for opening the issue, I'll try to do that soon!

**Comment by quentinblampey** [comment]
Indeed, it's very easy to add
I made a PR [here](https://github.com/bioconda/bioconda-recipes/pull/51367), I don't know how long it will take 🙂

**Comment by quentinblampey** [comment]
It has been merged, I'm closing this issue!
