### ISSUE TITLE
Sopa read issue

### ISSUE THREAD

**Issue by deborahha** [gustaveroussy/sopa#151]
Hi,

I am trying to use the sopa CLI with merscope data. 
When running the following: 
sopa read '/Sample/region_R2/' --technology merscope 
I get this error: KeyError: '.zgroup'. 

Do you know how I could solve this? 
Thanks,
Deborah

**Comment by quentinblampey** [comment]
Hello @deborahha, could you please send me the full error message?

**Comment by deborahha** [comment]
Hey @quentinblampey, sorry for the delay, I realized that I made a mistake and I had to use the --sdata-path, as it was trying to write the zarr file somewhere I did not have permission to write, I don't get an error now...

Thanks,
Deborah

**Comment by quentinblampey** [comment]
Alright, thanks for the update @deborahha, I'm closing the issue!
