### ISSUE TITLE
Patch # has < 4000 transcripts. Segmentation will not be run?

### ISSUE THREAD

**Issue by KunHHE** [gustaveroussy/sopa#157]
Hi,

If I run sopa patchify baysor, it said " Patch # has < 4000 transcripts. Segmentation will not be run on this patch.", is this normal by any chance, I can see some areas indeed has fewer transcript spots from the merscope data. 

Thanks for help!!!

(sopa) C:\Users\hekun>sopa patchify baysor C:/Users/hekun/Downloads/S3R1.zarr --config-path C:/Users/hekun/sopa/workflow/config/merscope/merscope.toml --patch-width-microns 1200 --patch-overlap-microns 50
C:\Users\hekun\miniconda3\envs\sopa\lib\site-packages\numba\core\decorators.py:246: RuntimeWarning: nopython is set for njit and is ignored
  warnings.warn('nopython is set for njit and is ignored', RuntimeWarning)
[INFO] (sopa.patches.patches) Writing sub-CSV for transcript segmentation
[########################################] | 100% Completed | 11.23 s
[INFO] (sopa.patches.patches) Patches saved in directory C:\Users\hekun\Downloads\S3R1.zarr\.sopa_cache\baysor_boundaries
[INFO] (sopa.patches.patches) Patch 0 has < 4000 transcripts. Segmentation will not be run on this patch.
[INFO] (sopa.patches.patches) Patch 11 has < 4000 transcripts. Segmentation will not be run on this patch.
[INFO] (sopa.patches.patches) Patch 15 has < 4000 transcripts. Segmentation will not be run on this patch.

**Comment by quentinblampey** [comment]
Hi @KunHHE, this is something that can be changed via the API. I'll release a new version of Sopa in about one week, so I'll give you more details about it after the release

The reason for doing this is that it's difficult to know when Baysor will crash (it usually crashes when there are not a lot of transcripts, but I have no precise way of knowing it beforehand). So, to avoid an unexpected Baysor crash, we filter out these patches.
In the next version of the API, you'll be able to control or remove this filter. Baysor may crash on some patches, but you'll be able to `force` resolving the segmentation.

**Comment by KunHHE** [comment]
Hi @quentinblampey, do you mind providing some guidance to force run Baysor that some patch has <4000 transcripts? Many thanks!
