### ISSUE TITLE
patch running for Baysor in CLI

### ISSUE THREAD

**Issue by KunHHE** [gustaveroussy/sopa#160]
Hi @quentinblampey, Thanks very much on the responding! My confused question is when running sopa-cellpose in the CLI: sopa patchify image C:/Users/hekun/Downloads/S3R1.zarr --patch-width-pixel 6000 --patch-overlap-pixel 150
sopa segmentation cellpose C:/Users/hekun/Downloads/S3R1.zarr --diameter 60 --channels DAPI --flow-threshold 2 --cellprob-threshold -6 --model-type cyto3 --min-area 1000 --clip-limit 0.2 --gaussian-sigma 1

So this command line will run all the patches (I have 49 here) for cellpose automatically;

However, when running Baysor:
sopa patchify baysor C:/Users/hekun/Downloads/S3R1.zarr --config- path C:/Users/hekun/sopa/workflow/config/merscope/merscope.toml --patch-width-microns 1200 --patch-overlap-microns 20;
cd C:/Users/hekun/Downloads/S3R1.zarr/.sopa_cache/baysor_boundaries/1;
C:/Users/hekun/.julia/bin/baysor run --polygon-format FeatureCollection -c /Users/hekun/sopa/workflow/config/merscope/merscope.toml transcripts.csv;

Will I have to run the patch one-by-one? so I have 15 patches here for Baysor? I know in the website it said can run snakemake or nextflow. But I run everything now in the CLI, and as mentioned earlier there's an issue running snakemake in windows.

Any quick comments can run it in line for all the patches?

Thansk a lot!

**Comment by quentinblampey** [comment]
Hi @KunHHE,

Yes, for now, the CLI should be used for each of the patch indices. This will be updated in `sopa==2.0.0` (which is expected to be released very soon, as mentioned in my answer to your other issue), so you'll be able to run on all patches directly. It will also add a parallelization backend with dask to make it faster.
