### ISSUE TITLE
Writing CosMX segmentation+transcripts to Xenium explorer

### ISSUE THREAD

**Issue by GBeattie** [gustaveroussy/sopa#162]
Hi!

I've a feeling this may not be in the scope of what Sopa was designed to do, but my goal (for the moment) has been simply to take the CosMX outputs and visualise them as is in the Xenium explorer (i.e. with the segmentation calculated by AtoMX).

I've managed to generate a Xenium explorer file however there are several elements missing:

1. All images except for the histone channel seem to be missing (they are available to select on the explorer, but don't appear)
2. No transcripts available
3. No segmentation available

No segmentation I expected, and I'm unsure if it's possible to include the original segmentation. I'll show below my workings and a screenshot of the explorer. Thanks in advance for any assistance!

```
>>> from sopa.io import cosmx
>>> from sopa.io import write
>>>
>>> sdata = cosmx("Sam_reseg_30_10_2024_15_42_51_118", dataset_id="L1_SU500")
[WARNING] (sopa.io.reader.cosmx) Image stitching is currently experimental
/lustre/scratch/scratch/regmgbe/Projects/Sopa/sopa_env/lib/python3.9/site-packages/sopa/io/reader/cosmx.py:236: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(transcripts_file, compression="gzip")
>>> sdata
SpatialData object
├── Images
│     └── 'stitched_image': DataTree[cyx] (5, 92832, 95975), (5, 46416, 47987), (5, 23208, 23993), (5, 11604, 11996), (5, 5802, 5998)
└── Points
      └── 'points': DataFrame with shape: (<Delayed>, 12) (3D points)
with coordinate systems:
    ▸ 'global', with elements:
        stitched_image (Images), points (Points)
>>> write("./sopa_out", sdata)
[WARNING] (sopa._sdata) sdata object has no valid segmentation boundary. Consider running Sopa segmentation first.
[WARNING] (sopa.io.explorer.converter) The argument 'gene_column' has to be provided to save the transcripts
[INFO] (sopa.io.explorer.images) Writing multiscale image with procedure=semi-lazy (load in memory when possible)
Writing tiles:   0%|          | 0/42770 [00:00<?, ?it/s][INFO] (sopa.io.explorer.images)    > Image of shape (5, 92832, 95975)
Writing tiles: 100%|█████████▉| 42769/42770 [6:37:52<00:00,  1.79it/s]
Writing tiles:   0%|          | 0/10810 [00:00<?, ?it/s][INFO] (sopa.io.explorer.images)    > Image of shape (5, 46416, 47987)
Writing tiles: 100%|█████████▉| 10809/10810 [2:45:33<00:00,  1.09it/s]
Writing tiles:   0%|          | 0/2760 [00:00<?, ?it/s][INFO] (sopa.io.explorer.images)    > Image of shape (5, 23208, 23993)
Writing tiles: 100%|█████████▉| 2759/2760 [1:11:43<00:01,  1.56s/it]
[INFO] (sopa.io.explorer.images)    (Loading image of shape (5, 11604, 11996)) in memory
[INFO] (sopa.io.explorer.images)    > Image of shape (5, 11604, 11996)
[INFO] (sopa.io.explorer.images)    > Image of shape (5, 5802, 5998)
[INFO] (sopa.io.explorer.images)    > Image of shape (5, 2901, 2999)
[INFO] (sopa.io.explorer.converter) Saved files in the following directory: sopa_out
[INFO] (sopa.io.explorer.converter) You can open the experiment with 'open sopa_out/experiment.xenium'
```

<img width="673" alt="image" src="https://github.com/user-attachments/assets/809d3aaa-72a4-4c53-8209-422f383178ee">

**Comment by quentinblampey** [comment]
Hi @GBeattie!

### Regarding the cell segmentation
Actually, we could visualize any segmentation we want in theory, even the segmentation from AtomX. The blocker is that Sopa does not add the AtomX segmentation inside the SpatialData object, because we normally aim to run segmentation with Sopa.

If you find a way to add the segmentation to the SpatialData object (as shapes), it should be able to open it in the Xenium Explorer.

### Regarding transcripts
In the current version of Sopa, you need to specify the name of the column containing the gene names (i.e., for CosMX, it should be `gene_column="target"`), else `sopa.io.write` doesn't know which are the gene names. Indeed, you can see the following warning:
```
[WARNING] (sopa.io.explorer.converter) The argument 'gene_column' has to be provided to save the transcripts
```

To save time, you can try only convert the transcripts, and keep the image / metadata you already have converted. That is, you can try:
```python
# the mode specifies that only the transcripts will be converted
write("./sopa_out", sdata, gene_column="target", mode="+t")
```

### Regarding the channel intensities
Maybe the original intensities are so low that they are very close to 0. Can you compute the maximum intensity per channel? This should be something like this:
```python
sdata["stitched_image"]["scale0"]["image"].max(dim=["y", "x"]).compute()
```

**Comment by GBeattie** [comment]
@quentinblampey Thanks for the tips!

I'll look into the segmentation and see if I can come up with a way of reading in the AtoMX output (I'm not terribly hopeful I'll manage but we'll see!).

For the transcripts, of course yes missed that, I'll give that a try.

I've ran that line to extract the channel intensities, looks to me as if they are fairly reasonable across channels, but may be mistaken:

```
>>> sdata["stitched_image"]["scale0"]["image"].max(dim=["y", "x"]).compute()
<xarray.DataArray 'image' (c: 5)> Size: 10B
array([3750, 4040, 2726, 2730, 3969], dtype=uint16)
Coordinates:
  * c        (c) <U7 140B 'Histone' 'G' 'DAPI' 'rRNA' 'GFAP'
```

**Comment by quentinblampey** [comment]
Okay, let me know!

For the channel intensity, it seems low compared to the max value. Indeed, the type is `uint16`, which means it goes up to 65536. For instance, 4000 is only 6% of the max value, meaning that you should see a few pixels of low intensity somewhere on the image.

You can try the following, to create a new image with clipped value to the 99th quantile:
```python
from sopa.io.reader.utils import _clip_intensity_values

sdata["clipped_intensities"] = _clip_intensity_values(sdata["he_image"]["scale0"]["image"])

# now, we precise which image we want to convert via `image_key`
# and, again, I convert only the image
 write("./sopa_out", sdata, mode="+i", image_key="clipped_intensities")
```

**Comment by GBeattie** [comment]
Thanks! Will report back on transcripts and image rescaling soon!

**Comment by GBeattie** [comment]
@quentinblampey I can confirm the image rescaling and transcripts are now working in the Xenium browser (images are looking better than in the AtoMx explorer in fact), thanks! Hoping I get some time before the holidays to investigate including the segmentation as well.

**Comment by quentinblampey** [comment]
Good to hear!
Regarding the segmentation, just out of curiosity, is there a reason why you prefer to use the AtomX segmentation rather than using Sopa?

**Comment by GBeattie** [comment]
As a facility provider I think it's best to keep our options open as segmentation choice will be down to the user, although I'd happily suggest to users to use Sopa, they may have reason to use AtoMx. So at the moment my main goal with Sopa is for it's Xenium explorer capabilities, as it's usability is much greater than AtoMx's viewer.

**Comment by quentinblampey** [comment]
Okay thanks for your comment @GBeattie, makes sense!

**Comment by lkmartin90** [comment]
Hi - Just wondering if you managed to find a way to include the segmentation? I'm running  into the same problem. Thanks!
