### ISSUE TITLE
AnnData h5ad from Scimap output is compatible with the Sopa package for Spatial statistics?

### ISSUE THREAD

**Issue by KunHHE** [gustaveroussy/sopa#170]
Dear @quentinblampey, trying the function of sopa for PhenoCycler tif images. Usually, the PhenoCycler images are 40+ channels, so the downstream annotation as suggested in the tutorial "If you have a large number of channels, it may be preferable to run clustering on your data, for instance, using [`Leiden clustering](https://scanpy.readthedocs.io/en/stable/generated/scanpy.tl.leiden.html). Then, you can annotate each cluster manually by plotting a heatmap of all channel expressions per cluster." 
I found a "[akoya_webinar_0622]" (https://github.com/adyprat/akoya_webinar_0622). It includes 3 steps, especially using scimap for cell-type annotation based on channels of images. Do you think I can newAD.write_h5ad, then import it back to the Sopa package for the "Spatial statistics" section? Do you think the AnnData from Scimap output is compatible with the Sopa package?

Thanks very much!!!

note:
Step1-DataImport.ipynb 
Step2-SNR.ipynb 
Step3-Phenotyping.ipynb 
Step4-SpatialScore.ipynb

**Comment by quentinblampey** [comment]
Hi @KunHHE, I saw you closed the issue, have you found the answers to all of your questions?

**Comment by KunHHE** [comment]
HI @quentinblampey, Thanks! I think as long as we have the h5ad file with proper area+niches annotation in the data structure using other tools, so we can go back to the sopa statistical pipeline.

**Comment by quentinblampey** [comment]
Nice! FYI, you can try [Novae](https://github.com/MICS-Lab/novae) to get the niches if you want
