### ISSUE TITLE
"niches" from demo data in Spatial statistics section

### ISSUE THREAD

**Issue by KunHHE** [gustaveroussy/sopa#171]
Dear @quentinblampey, Can I ask you where the "niches" in the spatial statistics section of DEMO data come from? We did not define a niche (like CODEX data) in the data processing using SOPA. So, without a niche definition, we cannot run downstream "niches"-related analyses.
Thanks very much!

**Comment by quentinblampey** [comment]
Hi @KunHHE, since you closed the issue, I assume you found the answer?

**Comment by KunHHE** [comment]
Hi @quentinblampey. Happy new year! I guess the "niches" and "area" in the DEMO page, it is assigned by other python tools before processing using spatial statistics? Thanks!

**Comment by quentinblampey** [comment]
Yes, the niches were computed by other tools, such as [Novae](https://github.com/MICS-Lab/novae) (which is also a tool I developed), but the area is computed by Sopa!
