### ISSUE TITLE
Where is the tuto.zarr from the tuto.zarr?

### ISSUE THREAD

**Issue by suhridbuddha** [gustaveroussy/sopa#38]
snakemake --config sdata_path=tuto.zarr --configfile=config/toy/uniform_cellpose.yaml --cores 1 --use-conda

i did not find the tuto.zarr in the workflow or anywhere in the snakemake folder

**Comment by quentinblampey** [comment]
Hello @suhridbuddha, the `tuto.zarr` directory should be located in the directory where you executed the pipeline, i.e. in the `workflow` directory.

Was the pipeline successfully executed? Do you have the `tuto.explorer` directory?
Can you try with an absolute path instead, for instance with `--config sdata_path=/path/to/tuto.zarr`?

**Comment by rocketeer1998** [comment]
I'm facing the same issue. Providing the absolute path does not solve this issue which alerts `AssertionError: Technology 'uniform' unknown. Currently available: xenium, merscope, cosmx, phenocycler, hyperion, macsima`. The pipeline didn't execute successfully. No `tuto.explorer` was found. My OS is Windows 10 64 bit.

**Comment by quentinblampey** [comment]
I couldn't reproduce the issue yet. Meanwhile, a few questions:
- Do you have the same issue with the CLI? For example, if you run the command line below, can you see `tuto.zarr`?
```sh
sopa read . --sdata-path tuto.zarr --technology uniform
```
- If the CLI doesn't work either, can you try the API? Try the Python code below:
```python
from sopa.utils.data import uniform

sdata = uniform()
sdata.write("tuto.zarr", overwrite=True)
```
- @suhridbuddha are you also on Windows?

**Comment by quentinblampey** [comment]
This is probably a Windows issue related to how strings are handled in the command line. This should be solved in the master branch, can you pull and try?
