### ISSUE TITLE
pip install

### ISSUE THREAD

**Issue by HSvitina** [gustaveroussy/sopa#39]
Dear developer. I have issues with installing/importing package through pip. I created new conda env python 3.10 and did 'pip install sopa', it was installed, but when I try to proceed 
import sopa.segmentation
ImportError: cannot import name '_get_unique_label_values_as_index' from 'spatialdata._core.query.relational_query' (C:\GBW_MyPrograms\Anaconda\envs\VPT\lib\site-packages\spatialdata\_core\query\relational_query.py)
Can you help me, please?

**Comment by quentinblampey** [comment]
Hello @HSvitina, thanks for reporting this issue. I think this is related to a newer version of `spatialdata-io`. Can you try to upgrade the two packages as below:
```sh
pip install spatialdata-io --upgrade
pip install spatialdata --upgrade
```
> You may have warnings during the pip install, because sopa depends `spatialdata < 0.1.0`, but just ignore the warning

I will soon release `sopa=1.0.7`, where this issue will be fixed, but the above solution should work in the meantime.

**Comment by HSvitina** [comment]
Thank you. Installation went well.
