### ISSUE TITLE
RuntimeError in rule patchify_cellpose: add_image(), add_labels(), add_points() and  add_shapes()

### ISSUE THREAD

**Issue by suhridbuddha** [gustaveroussy/sopa#43]
I am getting in this error at patchify stage:

RuntimeError: The functions add_image(), add_labels(), add_points() and 
add_shapes() have been removed in favor of dict-like access to the elements. 
Please use the following syntax to add an element:

        sdata.images["image_name"] = image
        sdata.labels["labels_name"] = labels
        ...

The new syntax does not automatically updates the disk storage, so you need to 
call sdata.write() when the in-memory object is ready to be saved.
To save only a new specific element to an existing Zarr storage please use the 
functions write_image(), write_labels(), write_points(), write_shapes() and 
write_table(). We are going to make these calls more ergonomic in a follow up 
PR.

any idea?

i am using snakemake-lsf profile (default setup) and xenium ome.tif

**Comment by quentinblampey** [comment]
Hello,

Yes, this is an issue related to the new version of Sopa (it solved a bug, but also created another one...). 
Sorry for this second issue, I'll fix this on Wednesday!

**Comment by suhridbuddha** [comment]
the sopa i have now is `Version: 1.0.6`. Do you think downgrade may help?

**Comment by suhridbuddha** [comment]
even with the tuto.zarr i am getting the same error now.

**Comment by quentinblampey** [comment]
Hello @suhridbuddha, the newest releases of spatialdata and spatialdata-io introduced some breaking changes, so I need to update Sopa. This will be done tonight or tomorrow morning. 

These changes came with the publication of SpatialData, but now there shouldn't have breaking changes anymore! Wait for the next Sopa release and it should be all fixed 😊

**Comment by quentinblampey** [comment]
I released `sopa==1.0.8`, can you try?
It should now work, even though I still need to check some new functionalities from spatialdata, and perform additional checks.

**Comment by suhridbuddha** [comment]
Thank you @quentinblampey. The new sopa has resolved the problem
