### ISSUE TITLE
[Feature] Use .CZI data in SOPA

### ISSUE THREAD

**Issue by mariavigovaldoleiros** [gustaveroussy/sopa#58]
**Feature request**
I am using multiplexed images (Opal dyes - fluorescence data) acquired with a Zeiss microscope that generates **.czi** files, but this format is not compatible with SOPA.

**Suggested solution**
Update PhenoCycler technology to accept .czi data as raw inputs. 

**Alternative**
Create a technology (e.g. ‘Opal System’) that accepts .czi as raw input.

_Thank you!_

**Comment by quentinblampey** [comment]
Hello @mariavigovaldoleiros, thanks for creating this issue, you're actually not the first one to ask for a `.czi` file reader. I'll work on this and come back to you very soon!

**Comment by quentinblampey** [comment]
This is available in `sopa==1.0.11`, via a new reader called [aicsimageio](https://gustaveroussy.github.io/sopa/api/io/#sopa.io.aicsimageio). It uses AICSImageIO, which supports reading multiple formats, including CZI.
Note that, as the docs mentions, you'll need to `pip install aicsimageio` and `pip install aicspylibczi`.

The usage is the same as the other readers, and the `path` argument refers to one CZI file.

Let me know how it goes!

**Comment by quentinblampey** [comment]
I'm closing this issue, but feel free to re-open if you need extra information!
