### ISSUE TITLE
[help wanted] Other segmentation options

### ISSUE THREAD

**Issue by cstrlln** [gustaveroussy/sopa#61]
Thanks for the software, it's a very comprehensive effort.
We just got some CosMX data and are pretty unhappy with the default segmentations. We were on the way of training Cellpose models with membrane fluorescence and getting good results when we ran into sopa, I see that we could include these models in the sopa pipeline. However we were also interested in testing more recent approaches like BIDCell or Bering, which I guess are similar to Baysor.
I would like to know how would you suggest implementing these tests with sopa, for example, maybe obtain segmentations and bring them into sopa and resolve the segmentation? how would one go around testing different segmentation pipelines.

I think this might be related to issue #55 

Any advice, suggestion how to move forward with this, or if you believe this defeats the purpose of this package would be appreciated.

**Comment by cstrlln** [comment]
Also, take a look at proseg, another image-free method, seems already handling well cosmx, merfish and xenium datasets.
https://github.com/dcjones/proseg

**Comment by quentinblampey** [comment]
Actually, we were testing proseg yesterday! It gave good results on our first test, and we will conduct additionnal tests.
It looks promising, so it's likely to be added inside Sopa :)

Also, their output and installation are consistent with Baysor, so adding this will be much easier than BIDCell. I'll probably try to add this in the next few weeks if our tests are convincing.

**Comment by cstrlln** [comment]
That's great, looks very promising.

**Comment by quentinblampey** [comment]
Hey @cstrlln, I just released a new version `1.1.1` of sopa, which now includes [ComSeg](https://github.com/fish-quant/ComSeg) by @tdefa!
We also contacted the author(s) of `proseg` to see if they want to add it to sopa.

Feel free to re-open if needed!

**Comment by KunHHE** [comment]
Hi @quentinblampey Any updates on the proseg added into sopa? That will be very cool!!!

**Comment by quentinblampey** [comment]
Hi @KunHHE, no update regarding Proseg, sorry (we are still discussing it with its author).

I'm also discussing with the author of [segger](https://github.com/EliHei2/segger_dev) to integrate it inside Sopa
