### ISSUE TITLE
[Feature] how to handle updated output from different technologies.

### ISSUE THREAD

**Issue by cstrlln** [gustaveroussy/sopa#62]
**Is your feature request related to a problem? Please describe.**
I think the output of CosMX files  has changed since sopa was developed.

**Describe the solution you'd like**
Could you suggest which files are the ones that sopa needs to read CosMX data properly.

The Morphology2D folder is the same, but the transcript files naming seems to have changed. Also, not sure which is the FOV location file needed. 

Maybe if you could point me to which minimum data is required for each file, or a file example.

Thank you

**Comment by quentinblampey** [comment]
Hello @cstrlln,

In this [section of the doc](https://gustaveroussy.github.io/sopa/api/io/#sopa.io.cosmx) you'll find details about which files are needed for CosMX data. Note that `path` is the path to the directory containing all these files.

Yet, maybe you have a different file structure, indeed. Can you give me an overview of the file structure that you have?

We might still need improvements on the CosMX reader, so your feedback will really help me improve it :)

**Comment by cstrlln** [comment]
The file structure is very long but, just took a few screenshots.
It looks to me that naming of files and columns might have changed substantially since the demo datasets.

[file_structure.pdf](https://github.com/gustaveroussy/sopa/files/15239294/file_structure.pdf)

**Comment by cstrlln** [comment]
I was looking more into this and Nanostring has an export module in github that might format the files similar to the demo dataset they put out, with flat file export:
https://github.com/Nanostring-Biostats/CosMxDACustomModules

I'm going to try that.

**Comment by Jwong684** [comment]
To piggyback off this thread, is there a way to configure custom headers to look at? CosMx's export currently doesn't generate files that look like the one in their Lung dataset

**Comment by quentinblampey** [comment]
Thanks @cstrlln, let me know how it goes!
Meanwhile, I will also try to find an export module that has the intended file format
