### ISSUE TITLE
Xenium Input File Change 

### ISSUE THREAD

**Issue by saito-k1** [gustaveroussy/sopa#68]
Along with CosMx, I believe the Xenium input files have also changed. It looks like in the current sopa version, it still searches for morphology_mip.ome.tif; however, in the new Xenium outputs they no longer have this file. Because of this, I get errors when I try to run the snakemake pipeline or when I attempt to load the data using sopa.io.xenium. Thank you for your help!

**Comment by quentinblampey** [comment]
Hi, thanks for reporting this issue. Do you still have a `morphology.ome.tif` file though? Or is it replaced by others files?

**Comment by saito-k1** [comment]
There is a morphology.ome.tif file as well as a morphology_focus directory that contains 4 different focus channels (DAPI, ATP1A1/CD45/E-Cadherin, 18S, and AlphaSMA/Vimentin). For now I've been changing the xenium.py file to access the morphology.ome.tif instead of the mip file! I believe the new format can be found here: https://www.10xgenomics.com/support/software/xenium-onboard-analysis/latest/analysis/xoa-output-understanding-outputs.

**Comment by saito-k1** [comment]
Thank you so much for releasing that so quickly! I have no issues when I load the data using the API now. When I try to run the snakemake pipeline though, I get this error: 

"Building DAG of jobs...
MissingInputException in rule to_spatialdata in file /scratch/ksa307/xenium/cellpose_baysor/sopa/workflow/Snakefile, line 22:
Missing input files for rule to_spatialdata:
    output: scratch/ksa307/xenium/cellpose_baysor/xeniumranger/output-XETG00118__0013339__Region_1__20240420__231535.zarr/.zgroup
    affected files:
        scratch/ksa307/xenium/cellpose_baysor/xeniumranger/output-XETG00118__0013339__Region_1__20240420__231535".

I receive the same error whether I try to run on the HPC or locally. The data path leads to my xenium output directory. Within the directory I have a morphology_focus directory that contains a DAPI focus image. Here is my command: "snakemake --profile slurm --config data_path=scratch/ksa307/xenium/output-XETG00118__0013339__Region_1__20240420__231535 --configfile=config/xenium/cellpose_baysor.yaml", which I run in the workflow folder of the cloned sopa repository. Do I need to add the channel name somewhere in here now that it's changed? Thank you for your help!

**Comment by quentinblampey** [comment]
Hello, according to your command, you use a relative path to specify your dataset. Can you try again with `/scratch/...` instead of `scratch/...`?
I.e., the full command:
```python

snakemake --profile slurm --config data_path=/scratch/ksa307/xenium/output-XETG00118__0013339__Region_1__20240420__231535 --configfile=config/xenium/cellpose_baysor.yaml
```

**Comment by saito-k1** [comment]
It's working now, sorry for the trouble and thank you for the help!!
