### ISSUE TITLE
Baysor boundaries index and Transcripts cell_id have minimal overlap

### ISSUE THREAD

**Issue by saito-k1** [gustaveroussy/sopa#87]
Good afternoon,

Back with one more question. I ran the snakemake pipeline with cellpose followed by baysor on Xenium data, and I've been exploring the resulting SpatialData object. I noticed that there is minimal overlap between the transcripts cell_id and the baysor boundaries index, while I would expect it to be close to 1:1. For example, in this dataset, there are 802713 total cells identified by Baysor. I would expect the transcript mapping to map back to these cells, but there are only about 100 cells that overlap between them.

Here is my quick script: 

sdata= spatialdata.read_zarr("~/Documents/data.zarr")
baysor_boundaries= sdata.shapes["baysor_boundaries"]
transcripts = sdata.points["transcripts"]
print(len(set(baysor_boundaries.index).intersection(transcripts.cell_id)))

Similarly, when I check the overlap between the cell_id column in my table.obs (anndata) and the cell_id column in transcripts, I still only get about 100 cells that are the same between them:
print(len(set(sdata.table.obs["cell_id"]).intersection(set(transcripts["cell_id"]))))

Is this the intended behavior of the workflow? Thank you for your help!

**Comment by quentinblampey** [comment]
Hello @saito-k1,

Here `sdata.points["transcripts"]` is the original transcript dataframe from the Xenium. For this file, the `cell_id` column comes from the Xenium segmentation, not the Sopa segmentation. Therefore, these cell IDs are not the cell IDs used by Baysor. So, it's expected not to have a large overlap; it's completely random!

We use the name naming convention as 10X-Genomics, so it seems the cell IDs are related, but it really comes from two distinct processes! The actual cell IDs from cellpose are not saved inside the `transcripts` dataframe, their are saved in cache files (which are deleted at the end of the pipeline)

**Comment by saito-k1** [comment]
Got it, so there is no way to access which cell each transcript was ultimately mapped to? I suppose that I would've expected the transcripts dataframe to contain the final mapping, rather than the original transcript dataframe from Xenium (since the data in there is no longer relevant if we use the cellpose/baysor pipeline)! Thank you for all your help!

**Comment by quentinblampey** [comment]
It's possible using [_map_transcript_to_cell](https://github.com/gustaveroussy/sopa/blob/e898b15786dcd2871e975032bd4cda02c2bf9a39/sopa/patches/patches.py#L404C29-L404C29). It's a little bit hidden (there is no docstrings), but you should be able to use it!

> I suppose that I would've expected the transcripts dataframe to contain the final mapping

I prefer not to alter the original data input (the transcripts and the image) for consistency with the company output, this is why I'm not updating the transcript dataframe
