### ISSUE TITLE
Strange polygon shapes at tile borders

### ISSUE THREAD

**Issue by pakiessling** [gustaveroussy/sopa#91]
Hi,

I optimized segmentation very nicely now and the output looks very nice.

One problem that still occurs is along the edges of the tiles that get created for cellpose.

![grafik](https://github.com/user-attachments/assets/60fc44fc-e5b5-4e1e-9e7b-d519d7a567dd)

In the viewer it almost looks like the polygons overlap.

But the polygons in the sdata also look strange:

![grafik](https://github.com/user-attachments/assets/950395ab-fad6-46ce-8d91-74b28d56165f)

Any idea what is happening?

I am using patch_width_pixel: 4096 patch_overlap_pixel: 820 but this is also happening with other values along all the edges of segmentation patches.

**Comment by pakiessling** [comment]
The squares do not happen too often luckily.

What effect does the overlap have? Will the same protein intensity / transcripts be assigned twice?

**Comment by quentinblampey** [comment]
Yes, the same protein intensity / transcript will be assigned twice

For transcripts, using Baysor should solve the issue, but for the proteins it's more difficult to solve. I think some people are developing more sophisticated aggregation methods than a simple average. E.g., pixels far from the nucleus would have a small weight when averaging the intensity if the corresponding neighbourhood cell is high for this protein.

**Comment by pakiessling** [comment]
ok, that's good to know.
Ty!
